# Week 3 Ansible Playbook

- hosts: webservers

  tasks:
    - name: Replace helloworld.js file
      copy:
        src: /home/ec2-user/wk3_ansible/helloworld.js
        dest: /home/ec2-user/helloworld.js
        owner: ec2-user
        group: ec2-user
        mode: 0644

    - name: Restart helloworld service
      service: name=helloworld state=restarted
      become: yes

    - name: Install MySQL
      become: yes
      yum:
        name: mysql-server
        state: installed
